src/SFA.DAS.Campaigns.UITests/Project/Tests/Pages/Employer/UnderstandingApprenticeshipBenefitsFundingPage.cs
https://dev.azure.com/sfa-gov-uk/Digital%20Apprenticeship%20Service/_releaseProgress?_a=release-environment-logs&releaseId=115428&environmentId=532378
=> Campaigns update

src/SFA.DAS.Framework/RegexHelper.cs, src/SFA.DAS.Login.Service/Project/Helpers/LegalEntitiesSqlDataHelper.cs, src/SFA.DAS.Registration.UITests/Project/Features/ExistingAccountNavigation/RE_EAN_01.feature, src/SFA.DAS.Registration.UITests/Project/Features/ExistingAccountNavigation/RE_EAN_02.feature, src/SFA.DAS.Registration.UITests/Project/Features/ExistingAccountNavigation/RE_EAN_03.feature, src/SFA.DAS.Registration.UITests/Project/Helpers/EmployerPortalLoginHelper.cs, src/SFA.DAS.Registration.UITests/Project/Hooks.cs, src/SFA.DAS.Registration.UITests/Project/Pages/CreateAnAccountToManageApprenticeshipsPage.cs, src/SFA.DAS.Registration.UITests/Project/Pages/HomePage.cs, src/SFA.DAS.Registration.UITests/Project/Pages/InterimPages/InterimEmployerBasePage.cs, src/SFA.DAS.Registration.UITests/Project/Pages/RegistrationBasePage.cs, src/SFA.DAS.Registration.UITests/Project/Pages/YourOrganisationsAndAgreementsPage.cs, src/SFA.DAS.Registration.UITests/Project/Pages/YouveLoggedOutPage.cs, src/SFA.DAS.Registration.UITests/Project/RegistrationConfigurationSetup.cs, src/SFA.DAS.Registration.UITests/Project/Steps/ExistingAccountSteps.cs, src/SFA.DAS.Registration.UITests/specflow.json
https://dev.azure.com/sfa-gov-uk/Digital%20Apprenticeship%20Service/_releaseProgress?_a=release-environment-logs&releaseId=115561&environmentId=532875
=> Registration : Navigation tests

src/SFA.DAS.FATe.UITests/Project/Tests/Pages/FATeBasePage.cs, src/SFA.DAS.FATe.UITests/Project/Tests/StepDefinitions/VerifyLinksSteps.cs
Test results :- https://sfa-gov-uk.visualstudio.com/Digital%20Apprenticeship%20Service/_releaseProgress?_a=release-pipeline-progress&releaseId=115807
=> Updted the navigation steps

src/SFA.DAS.Login.Service/Project/Helpers/LoginUser.cs, src/SFA.DAS.Registration.UITests/Project/Features/AddOrgAndSignAgreement/RE_AOASA_01.feature, src/SFA.DAS.Registration.UITests/Project/Features/CreateEmpAccountOfCompanyType-NonLevy/RE_CEACMPT_01.feature, src/SFA.DAS.Registration.UITests/Project/Features/CreateEmpAccountOfCompanyType-NonLevy/RE_CEACMPT_02.feature, src/SFA.DAS.Registration.UITests/Project/Features/CreateEmpAccountOfCompanyType-NonLevy/RE_CEACMPT_03.feature, src/SFA.DAS.Registration.UITests/Project/Features/CreateEmpAccountOfPublicSectorType-NonLevy/RE_CEAPST_01.feature, src/SFA.DAS.Registration.UITests/Project/Features/CreateEmpAccountOfPublicSectorType-NonLevy/RE_CEAPST_02.feature, src/SFA.DAS.Registration.UITests/Project/Features/CreateLevyEmpAccountAndCheckDBFlag/RE_CLEA_01.feature, src/SFA.DAS.Registration.UITests/Project/Features/CreateLevyEmpAccountAndCheckDBFlag/RE_CLEA_02.feature, src/SFA.DAS.Registration.UITests/Project/Features/CreateLevyEmpAccountAndCheckDBFlag/RE_CLEA_03.feature, src/SFA.DAS.Registration.UITests/Project/Features/CreateMultipleEmpAccounts/RE_CMEA_01.feature, src/SFA.DAS.Registration.UITests/Project/Features/ManagePAYESchemes/RE_MPS_01.feature, src/SFA.DAS.Registration.UITests/Project/Features/ManagePAYESchemes/RE_MPS_02.feature, src/SFA.DAS.Registration.UITests/Project/Features/ManageTeamMembers/RE_MTM_01.feature, src/SFA.DAS.Registration.UITests/Project/Features/OrganisationDetailsChange/RE_ODC_01.feature, src/SFA.DAS.Registration.UITests/Project/Features/OrganisationDetailsChange/RE_ODC_02.feature, src/SFA.DAS.Registration.UITests/Project/Features/OrganisationDetailsChange/RE_ODC_03.feature, src/SFA.DAS.Registration.UITests/Project/Helpers/AccountCreationStepsHelper.cs, src/SFA.DAS.Registration.UITests/Project/Pages/EmpAccountCreationBase.cs, src/SFA.DAS.Registration.UITests/Project/Pages/HomePage.cs, src/SFA.DAS.Registration.UITests/Project/Pages/InterimPages/InterimEmployerBasePage.cs, src/SFA.DAS.Registration.UITests/Project/Pages/StubPages/StubYouHaveSignedInEmployerPage.cs, src/SFA.DAS.Registration.UITests/Project/Pages/YourOrganisationsAndAgreementsPage.cs, src/SFA.DAS.Registration.UITests/Project/Pages/YouveLoggedOutPage.cs, src/SFA.DAS.Registration.UITests/Project/Steps/AddOrRemoveOrgSteps.cs, src/SFA.DAS.Registration.UITests/Project/Steps/CreateAccountSteps.cs, src/SFA.DAS.Registration.UITests/Project/Steps/OrganisationDetailsChangeSteps.cs, src/SFA.DAS.Registration.UITests/Project/Steps/TeamMemberSteps.cs
https://dev.azure.com/sfa-gov-uk/Digital%20Apprenticeship%20Service/_releaseProgress?releaseId=115929&environmentId=534256&_a=release-environment-logs
=> Registration : Tests migration part 1

src/SFA.DAS.EmployerFinance.UITests/Project/Tests/Features/FinancePagesExistingUser/EF_FPEU_01.feature, src/SFA.DAS.EmployerFinance.UITests/Project/Tests/Features/FinancePagesNewUser/EF_FPNU_01.feature, src/SFA.DAS.EmployerFinance.UITests/Project/Tests/Features/FundingProjection/EF_FP_01.feature, src/SFA.DAS.EmployerFinance.UITests/Project/Tests/Features/HomePageFinanceLinksNewUser/EF_HPFLNU_01.feature, src/SFA.DAS.EmployerFinance.UITests/Project/Tests/Features/HomePageFinanceLinksNewUser/EF_HPFLNU_02.feature, src/SFA.DAS.EmployerFinance.UITests/Project/Tests/Features/HomePageFinanceLinksNewUser/EF_HPFLNU_03.feature, src/SFA.DAS.EmployerFinance.UITests/Project/Tests/Features/HomePageFinanceLinksNewUser/EF_HPFLNU_04.feature, src/SFA.DAS.EmployerFinance.UITests/Project/Tests/Features/Navigation/EF_Nav_01.feature, src/SFA.DAS.EmployerFinance.UITests/Project/Tests/Pages/FinancePage.cs, src/SFA.DAS.EmployerFinance.UITests/Project/Tests/Steps/EmployerFinanceSteps.cs, src/SFA.DAS.EmployerFinance.UITests/SFA.DAS.EmployerFinance.UITests.csproj, src/SFA.DAS.EmployerFinance.UITests/Usings.cs, src/SFA.DAS.EmployerFinance.UITests/appsettings.Environment.json, src/SFA.DAS.EmployerFinance.UITests/appsettings.Project.json, src/SFA.DAS.EmployerFinance.UITests/specflow.json, src/SFA.DAS.Registration.UITests/Project/Pages/AboutYourAgreementPage.cs, src/SFA.DAS.Registration.UITests/Project/Pages/HomePage.cs, src/SFA.DAS.Registration.UITests/Project/Pages/InterimPages/InterimEmployerBasePage.cs, src/SFA.DAS.Registration.UITests/Project/Pages/InterimPages/InterimHomeBasePage.cs, src/SFA.DAS.Registration.UITests/Project/Pages/YourOrganisationsAndAgreementsPage.cs, src/SFA.DAS.Registration.UITests/Project/Steps/CreateAccountSteps.cs, src/SFA.DAS.TestAutomation.sln
https://dev.azure.com/sfa-gov-uk/Digital%20Apprenticeship%20Service/_releaseProgress?releaseId=116432&environmentId=536124&_a=release-environment-logs
=> Employer finance project migration completed

src/SFA.DAS.DfeAdmin.Service/Project/Helpers/SetDfeAdminCredsHelper.cs, src/SFA.DAS.DfeAdmin.Service/Project/Tests/LandingPage/ASAdminLandingPage.cs, src/SFA.DAS.ManagingStandards.UITests/Project/Helpers/MS_DataHelper.cs, src/SFA.DAS.ManagingStandards.UITests/Project/Helpers/ManagingStandardsDataHelpers.cs, src/SFA.DAS.ManagingStandards.UITests/Project/Helpers/ManagingStandardsSqlDataHelper.cs, src/SFA.DAS.ManagingStandards.UITests/Project/Hooks/ManagingStandardsHooks.cs, src/SFA.DAS.ManagingStandards.UITests/Project/ManagingStandardsConfigurationSetup.cs, src/SFA.DAS.ManagingStandards.UITests/Project/Tests/Features/MS_01_ReviewApproveEditStandard.feature, src/SFA.DAS.ManagingStandards.UITests/Project/Tests/Features/MS_02_AddTrainingVenues.feature, src/SFA.DAS.ManagingStandards.UITests/Project/Tests/Features/MS_03_Add_DeleteStandard.feature, src/SFA.DAS.ManagingStandards.UITests/Project/Tests/Features/MS_04_TribalUpdateProviderInfo.feature, src/SFA.DAS.ManagingStandards.UITests/Project/Tests/Pages/ManagingStandardsProviderHomePage.cs, src/SFA.DAS.ManagingStandards.UITests/Project/Tests/Pages/Moderation/Moderation_CheckProviderUpdatePage.cs, src/SFA.DAS.ManagingStandards.UITests/Project/Tests/Pages/Moderation/Moderation_HomePage.cs, src/SFA.DAS.ManagingStandards.UITests/Project/Tests/Pages/Moderation/Moderation_ProviderDetailsPage.cs, src/SFA.DAS.ManagingStandards.UITests/Project/Tests/Pages/Moderation/Moderation_SearchPage.cs, src/SFA.DAS.ManagingStandards.UITests/Project/Tests/Pages/Moderation/Moderation_UpdateProviderPage.cs, src/SFA.DAS.ManagingStandards.UITests/Project/Tests/Steps/MS_AddAndDelete_Steps.cs, src/SFA.DAS.ManagingStandards.UITests/Project/Tests/Steps/MS_Moderation_Steps.cs, src/SFA.DAS.ManagingStandards.UITests/Project/Tests/Steps/MS_TrainingVenue_Steps.cs, src/SFA.DAS.ManagingStandards.UITests/Project/Tests/Steps/MS_YourDetails_Steps.cs, src/SFA.DAS.ManagingStandards.UITests/SFA.DAS.ManagingStandards.UITests.csproj, src/SFA.DAS.ManagingStandards.UITests/Usings.cs, src/SFA.DAS.ManagingStandards.UITests/appsettings.Environment.json, src/SFA.DAS.ManagingStandards.UITests/appsettings.Project.json, src/SFA.DAS.ManagingStandards.UITests/specflow.json, src/SFA.DAS.TestAutomation.sln
https://dev.azure.com/sfa-gov-uk/Digital%20Apprenticeship%20Service/_releaseProgress?releaseId=118046&environmentId=542650&_a=release-environment-logs
=> Managing standards migration

src/SFA.DAS.Approvals.UITests/Project/Tests/Features/AP_01_PortalLogin.feature, src/SFA.DAS.Approvals.UITests/Project/Tests/Features/AP_02_EmployerLogin.feature, src/SFA.DAS.Approvals.UITests/Project/Tests/Steps/AP_Steps.cs, src/SFA.DAS.Approvals.UITests/SFA.DAS.Approvals.UITests.csproj, src/SFA.DAS.Approvals.UITests/Usings.cs, src/SFA.DAS.Approvals.UITests/appsettings.Environment.json, src/SFA.DAS.Approvals.UITests/appsettings.Project.json, src/SFA.DAS.Approvals.UITests/specflow.json, src/SFA.DAS.ProviderLogin.Service/Project/Helpers/ProviderHomePageStepsHelper.cs, src/SFA.DAS.TestAutomation.sln
https://dev.azure.com/sfa-gov-uk/Digital%20Apprenticeship%20Service/_releaseProgress?releaseId=118683&environmentId=545501&_a=release-environment-logs
=> Approvals project : initial setup

src/SFA.DAS.FATe.UITests/Project/Tests/Features/E2E/E2E01TrainingProviderDetails.Feature, src/SFA.DAS.FATe.UITests/Project/Tests/Pages/FATeBasePage.cs, src/SFA.DAS.FATe.UITests/Project/Tests/Pages/ShortlistPage.cs, src/SFA.DAS.FATe.UITests/Project/Tests/Pages/Specific_TrainingProviderPage.cs, src/SFA.DAS.FATe.UITests/Project/Tests/Pages/TrainingProvidersPage.cs, src/SFA.DAS.FATe.UITests/Project/Tests/StepDefinitions/E2ESteps.cs, src/SFA.DAS.FATe.UITests/Project/Tests/StepDefinitions/ShortlistSteps.cs
Test results :- https://sfa-gov-uk.visualstudio.com/Digital%20Apprenticeship%20Service/_releaseProgress?_a=release-environment-logs&releaseId=118646&environmentId=545354
=> End to end Test added

src/SFA.DAS.EmployerFinance.UITests/Project/Tests/Features/Navigation/EF_Nav_01.feature, src/SFA.DAS.EmployerFinance.UITests/Project/Tests/Steps/EmployerFinanceSteps.cs, src/SFA.DAS.EmployerPortal.UITests/Project/Features/ExistingAccountNavigation/RE_EAN_01.feature, src/SFA.DAS.EmployerPortal.UITests/Project/Pages/InterimPages/InterimEmployerBasePage.cs, src/SFA.DAS.EmployerPortal.UITests/Project/Steps/ExistingAccountSteps.cs
E2-das-p-employerportal-automation-test-suite| https://sfa-gov-uk.visualstudio.com/Digital%20Apprenticeship%20Service/_releaseProgress?_a=release-environment-extension&releaseId=118639&environmentId=545316&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab
E2-das-p-employerfinance-automation-test-suite| https://sfa-gov-uk.visualstudio.com/Digital%20Apprenticeship%20Service/_releaseProgress?_a=release-environment-extension&releaseId=118648&environmentId=545364&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab
=> AddedAccessibilityStatementStepsForEmployerFinance&EmployerPortal

src/SFA.DAS.ManagingStandards.UITests/Project/Helpers/ManagingStandardsDataHelpers.cs, src/SFA.DAS.ManagingStandards.UITests/Project/Tests/Pages/ManagingStandardsProviderHomePage.cs
Fate :- Test passed
Managing standards:- one new test failing due to data issue. I will look and fix it.
=> Fixed failing tests

src/SFA.DAS.ManagingStandards.UITests/Project/Tests/Pages/ManagingStandardsProviderHomePage.cs, src/SFA.DAS.ManagingStandards.UITests/Project/Tests/Steps/MS_YourDetails_Steps.cs
All test passed :- https://sfa-gov-uk.visualstudio.com/Digital%20Apprenticeship%20Service/_releaseProgress?_a=release-pipeline-progress&releaseId=119124
=> Regulated standard flow updated

src/SFA.DAS.SupportTools.UITests/Project/Tests/Pages/SearchHomePage.cs, src/SFA.DAS.SupportTools.UITests/Project/Tests/Steps/MaSteps.cs
E2-das-p-support-tools-automation-test-suite| [E2-das-p-support-tools-automation-test-suite - Release-134 - Pipelines](https://sfa-gov-uk.visualstudio.com/Digital%20Apprenticeship%20Service/_releaseProgress?_a=release-environment-extension&releaseId=119466&environmentId=548727&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab)
=> SearchWithEmployerAccountName

src/SFA.DAS.EarlyConnectForms.UITests/Project/Helpers/EarlyConnectDataHelper.cs, src/SFA.DAS.EarlyConnectForms.UITests/Project/Helpers/EarlyConnectSqlHelper.cs, src/SFA.DAS.EarlyConnectForms.UITests/Project/Helpers/EarlyConnectStepsHelper.cs, src/SFA.DAS.EarlyConnectForms.UITests/Project/Hooks.cs, src/SFA.DAS.EarlyConnectForms.UITests/Project/Tests/Features/EducationalOrganisation.feature, src/SFA.DAS.EarlyConnectForms.UITests/Project/Tests/Features/NonUcasStudentJourney.feature, src/SFA.DAS.EarlyConnectForms.UITests/Project/Tests/Pages/EarlyConnectHomePage.cs, src/SFA.DAS.EarlyConnectForms.UITests/Project/Tests/Steps/NonUcasStudentJourneyStepDefinitions.cs, src/SFA.DAS.EarlyConnectForms.UITests/SFA.DAS.EarlyConnectForms.UITests.csproj, src/SFA.DAS.EarlyConnectForms.UITests/Usings.cs, src/SFA.DAS.EarlyConnectForms.UITests/appsettings.Environment.json, src/SFA.DAS.EarlyConnectForms.UITests/appsettings.Project.BrowserStack.json, src/SFA.DAS.EarlyConnectForms.UITests/appsettings.Project.json, src/SFA.DAS.EarlyConnectForms.UITests/specflow.json, src/SFA.DAS.Framework/UrlConfig.cs, src/SFA.DAS.TestAutomation.sln
https://dev.azure.com/sfa-gov-uk/Digital%20Apprenticeship%20Service/_releaseProgress?releaseId=119810&environmentId=550053&_a=release-environment-logs
=> Earlyconnect project migration

src/SFA.DAS.ManagingStandards.UITests/Project/Helpers/ManagingStandardsDataHelpers.cs, src/SFA.DAS.ManagingStandards.UITests/Project/Tests/Pages/ManagingStandardsProviderHomePage.cs, src/SFA.DAS.ManagingStandards.UITests/Project/Tests/Steps/MS_TrainingVenue_Steps.cs
Test results :- All tests passed https://sfa-gov-uk.visualstudio.com/Digital%20Apprenticeship%20Service/_releaseProgress?_a=release-pipeline-progress&releaseId=119855
=> Updated the tests

src/SFA.DAS.EPAO.UITests/Project/Helpers/EPAOHomePageHelper.cs, src/SFA.DAS.EPAO.UITests/Project/Helpers/SqlHelpers/EPAOApplySqlDataHelper.cs, src/SFA.DAS.EPAO.UITests/Project/Tests/Features/Apply/EPAO_AP_01.feature, src/SFA.DAS.EPAO.UITests/Project/Tests/Features/AssessmentOpportunity/EPAO_AO_01.feature, src/SFA.DAS.EPAO.UITests/Project/Tests/Features/AssessmentOpportunity/EPAO_AO_02.feature, src/SFA.DAS.EPAO.UITests/Project/Tests/Features/AssessmentOpportunity/EPAO_AO_03.feature, src/SFA.DAS.EPAO.UITests/Project/Tests/Pages/AO_HomePage.cs, src/SFA.DAS.EPAO.UITests/Project/Tests/Pages/AP_PR1_SearchForYourOrganisationPage.cs, src/SFA.DAS.EPAO.UITests/Project/Tests/Pages/Admin/StaffDashboardPage.cs, src/SFA.DAS.EPAO.UITests/Project/Tests/Pages/AssessmentService/AS_LandingPage.cs, src/SFA.DAS.EPAO.UITests/Project/Tests/Steps/ApplySteps.cs, src/SFA.DAS.EPAO.UITests/Project/Tests/Steps/AssessmentOpportunitySteps.cs, src/SFA.DAS.EPAO.UITests/Project/Tests/Steps/EPAOBaseSteps.cs, src/SFA.DAS.EmployerPortal.UITests/Project/Pages/CreateAnAccountToManageApprenticeshipsPage.cs, src/SFA.DAS.FATe.UITests/Project/Tests/Pages/FATeHomePage.cs, src/SFA.DAS.Framework/BasePage.cs, src/SFA.DAS.ProviderLogin.Service/Project/Pages/ProviderHomePage.cs
https://dev.azure.com/sfa-gov-uk/Digital%20Apprenticeship%20Service/_releaseProgress?releaseId=120747&environmentId=553765&_a=release-environment-logs
=> Epao project : migration 

src/SFA.DAS.FindEPAO.UITests/Project/Helpers/FindEPAOStepsHelper.cs, src/SFA.DAS.FindEPAO.UITests/Project/Hooks.cs, src/SFA.DAS.FindEPAO.UITests/Project/ObjectContextExtention.cs, src/SFA.DAS.FindEPAO.UITests/Project/Tests/Features/FEPAO_SearchAndSelectIntegratedStandard.feature, src/SFA.DAS.FindEPAO.UITests/Project/Tests/Features/FEPAO_SearchAndSelectStandardWithEPAO.feature, src/SFA.DAS.FindEPAO.UITests/Project/Tests/Features/FEPAO_SearchAndSelectStandardWithNoEPAO.feature, src/SFA.DAS.FindEPAO.UITests/Project/Tests/Features/FEPAO_SearchAndSelectStandardWithSingleEPAO.feature, src/SFA.DAS.FindEPAO.UITests/Project/Tests/Pages/FindEPAOIndexPage.cs, src/SFA.DAS.FindEPAO.UITests/Project/Tests/Steps/FindEPAOSteps.cs, src/SFA.DAS.FindEPAO.UITests/SFA.DAS.FindEPAO.UITests.csproj, src/SFA.DAS.FindEPAO.UITests/Usings.cs, src/SFA.DAS.FindEPAO.UITests/appsettings.Environment.json, src/SFA.DAS.FindEPAO.UITests/appsettings.Project.json, src/SFA.DAS.FindEPAO.UITests/specflow.json, src/SFA.DAS.TestAutomation.sln
https://dev.azure.com/sfa-gov-uk/Digital%20Apprenticeship%20Service/_releaseProgress?releaseId=120829&environmentId=554085&_a=release-environment-logs
=> Epao : Findepao project

src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Helpers/ApprenticeStepsHelper.cs, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Hooks/AANHooks.cs, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Features/Apprentice/AAN_A_01_Onboarding.feature, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Features/Apprentice/AAN_A_02_NegativePath.feature, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Features/Apprentice/AAN_A_03_SignUpEvents.feature, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Features/Apprentice/AAN_A_04_FilterAllEvents.feature, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Features/Apprentice/AAN_A_05_FilterAllEventsNetworkDirectory.feature, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Features/Apprentice/AAN_A_06_VerifyAndUpdateAmbassadorProfile.feature, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Features/Apprentice/AAN_A_07_VerifyApprenticeProfileAndSendMessage.feature, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Features/Apprentice/AAN_A_08_VerifyRegionalChairProfileAndSendMessage.feature, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Features/Apprentice/AAN_A_09_HideAndDisplayAmbassadorProfile.feature, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Pages/AppEmpCommonPages/AppEmpCommonBasePage.cs, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Pages/AppEmpCommonPages/ApprenticeMessagePage.cs, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Pages/AppEmpCommonPages/SearchNetworkEventsPage.cs, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Pages/AppEmpCommonPages/YourAmbassadorProfilePage.cs, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Pages/Apprentice/Apprentice_NetworkHubPage.cs, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Pages/Apprentice/BeforeYouStart.cs, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Pages/Apprentice/SignInPage.cs, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Pages/Apprentice/StubPages/StubSignInApprenticeAccountsPage.cs, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Pages/Apprentice/StubPages/StubYouHaveSignedInApprenticeAccountsPage.cs, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Pages/SearchEventsBasePage.cs, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Steps/AppEmp_BaseSteps.cs, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Steps/Apprentice/Apprentice_AcccessDenied_Steps.cs, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Steps/Apprentice/Apprentice_BaseSteps.cs, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Steps/Apprentice/Apprentice_Onboarding_Steps.cs, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Steps/Apprentice/Apprentice_Steps.cs, src/SFA.DAS.ApprenticeAmbassadorNetwork.UITests/Project/Tests/Steps/Employer/Employer_Steps.cs, src/SFA.DAS.EmployerPortal.UITests/Project/Pages/AccessDeniedPage.cs, src/SFA.DAS.Framework/BasePage.cs, src/SFA.DAS.Login.Service/Project/Helpers/StubSignInBasePage.cs
https://dev.azure.com/sfa-gov-uk/Digital%20Apprenticeship%20Service/_releaseProgress?_a=release-environment-logs&releaseId=121508&environmentId=556734
=> Aan apprentice test scenarios

src/SFA.DAS.Approvals.UITests/Project/Features/01_PreApprovals/08_GnS/AP_GnS_03_VerifyAgeChecksOnFoundationLevelCoursesPostApproval.feature, src/SFA.DAS.Approvals.UITests/SFA.DAS.Approvals.UITests.csproj
https://sfa-gov-uk.visualstudio.com/Digital%20Apprenticeship%20Service/_releaseProgress?_a=release-environment-logs&releaseId=121786&environmentId=557821
=> applied approvals tag

APP_as-p-apprentice-website/azure-pipelines.yml, APP_das-p-earlyconnect-forms/azure-pipelines.yml, E2_as-p-approvals/azure-pipelines.yml, E2_as-p-employer-account/azure-pipelines.yml, E2_as-p-employerfinance/azure-pipelines.yml, E2_as-p-support-console/azure-pipelines.yml, P1_as-p-fat/azure-pipelines.yml, P1_as-p-managing-standards/azure-pipelines.yml, P1_as-p-provider-account/azure-pipelines.yml, P2_as-p-epao/azure-pipelines.yml, P2_as-p-rat/azure-pipelines.yml, code-build.yml, deploy.yml
- Modified code-build.yml to include an input parameter for the projects that are to be built during a pipeline run and updated the service pipeline files with the values of projects to be built.
- Modified deploy.yml to pass in the test assembly parameter correctly
=> parameterised projects to build

src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/AddJourney/ConfirmDetailsPage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/AddJourney/NoResultsPage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/AddJourney/OfferApprenticeshipsPage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/AddJourney/OfferQualificationsPage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/AddJourney/OrganisationsDetailPage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/AddJourney/OrganisationsPage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/AddJourney/ProviderRoutePage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/AddJourney/SuccessfullyAddedPage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/AddJourney/UKPRNPage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/AddJourney/WhatQualificationsPage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/SearchAndUpdate/DoTheyOfferApprenticeshipsPage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/SearchAndUpdate/DoTheyOfferOtherQualificationsPage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/SearchAndUpdate/ManageTrainingProviderInformationPage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/SearchAndUpdate/ProviderDetailsPage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/SearchAndUpdate/SearchForTrainingProviderPage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/SearchAndUpdate/StatusChangePage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/SearchAndUpdate/SuccessPage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/SearchAndUpdate/TypeOfOrganisationPage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/SearchAndUpdate/TypeOfQualificationsPage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Pages/UKPRNAllowListPage.cs, src/SFA.DAS.AparAdmin.UITests/Project/Tests/Steps/AparAdminLoginSteps.cs
Added pages and some basic methods. The pages are yet to be developed.
=> Pages added for add and search

src/SFA.DAS.EmployerPortal.UITests/Project/Pages/InterimPages/InterimEmployerBasePage.cs
https://sfa-gov-uk.visualstudio.com/Digital%20Apprenticeship%20Service/_releaseProgress?_a=release-environment-logs&releaseId=122826&environmentId=561836
=> added delay before validation

src/SFA.DAS.DfeAdmin.Service/Project/Tests/Pages/DfeSignInPage.cs, src/SFA.DAS.Login.Service/Project/Helpers/CheckPage.cs
https://dev.azure.com/sfa-gov-uk/Digital%20Apprenticeship%20Service/_releaseProgress?releaseId=123026&environmentId=562605&_a=release-environment-logs
https://dev.azure.com/sfa-gov-uk/Digital%20Apprenticeship%20Service/_releaseProgress?_a=release-environment-logs&releaseId=123027&environmentId=562609
=> Dfe sign fix
